# Cipher Configuration
# ---
# If changed, project WILL STOP working, there is NO WAY AROUND if keys are lost or changed!
# Do NOT change these keys at ANY POINT AFTER INITIALISATION OF PROJECT! DO NOT!

# Primary Cipher Key
primary: "Primary Cipher Key1"
# Secondary Key
secondary: "Secondary Key1"
# Users models encryption
users: "Users models encryption1"
# Project models encryption
project: "Project models encryption1"
# Misc encryption
misc: "Misc encryption1"
